# Generated by Django 4.0.1 on 2023-05-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uaddress',
            old_name='email_address',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='uaddress',
            name='full_name',
        ),
        migrations.AddField(
            model_name='uaddress',
            name='add1',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='uaddress',
            name='add2',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='uaddress',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='uaddress',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='uaddress',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='uaddress',
            name='zip',
            field=models.IntegerField(default=0),
        ),
    ]
